// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models

module.exports = (mongoose, Mongoose) => {
  // This section contains the properties of your model, mapped to your collection's properties.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const schema = Mongoose.Schema(
    {
      name: { type: String, required: true, unique: true },
      picture: { type: Mongoose.Schema.Types.Mixed, default: {} },
      ean: Number,
      nutriScore: { type: String, default: "" },
      ecoScore: { type: String, default: "" },
      promotions: { type: Object, default: {} },
    },
    {
      timestamps: false,
    }
  );

  return mongoose.model("products", schema, "products");
};
